services:
  - type: web
    name: event-categorizer
    env: python
    plan: free
    buildCommand: ""
    startCommand: uvicorn app:app --host 0.0.0.0 --port 10000
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: XANO_ENDPOINT
        sync: false
